Add "suicide" and "suicidal" and others
snguyenthanh/better_profanity pull request #44
Opened 2022-04-20 17:01 UTC by theycallhermax

Adds some more profane words.

2022-04-20 17:03 UTC, meltfrommeltland approved these changes

2022-04-20 17:04 UTC, meltfrommeltland commented
oops

2022-04-20 17:05 UTC, Mwalters75 commented
> oops

Hello.

2022-04-21 00:05 UTC, Melt2002 requested changes
Remove racist, racism, farted, farting, wee, devil, satan, 666, hobo, butt, and satanists.

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +farted
Remove this

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +farting
Remove this

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +wee
Remove this

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +farted
Makes no sense to be on there

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +farting
Same reason as farted

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +wee
Wee isn't profanity

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +devil
Remove this, it's not necessary

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +satan
Remove this, same reason as devil.

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +666
Remove this, also same reason as devil

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +satanist
Remove this, no need for religions to be blacklisted

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +hobo
Remove this, not needed.

2022-04-21 00:05 UTC, Melt2002 commented on better_profanity/profanity_wordlist.txt
> +satanists
Remove this, same reason as satanist.

2024-08-12 08:55 UTC, closed without merging